version: 0.0
os: linux
files:
  - source: /vendor/
    destination: /home/ec2-user/serverpod/upload/vendor/
  - source: /journal_custom_server/
    destination: /home/ec2-user/serverpod/upload/journal_custom_server/
hooks:
  BeforeInstall:
    - location: journal_custom_server/deploy/aws/scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: journal_custom_server/deploy/aws/scripts/start_server
      timeout: 300
      runas: root
